apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: datanode
spec:
  serviceName: "datanode"
  replicas: 2
  selector:
    matchLabels:
      app: datanode
  template:
    metadata:
      labels:
        app: datanode
    spec:
      containers:
      - name: datanode
        image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
        envFrom:
        - configMapRef:
            name: hadoop-config
        # --- THÊM CÁC BIẾN MÔI TRƯỜNG ---
        env:
        # 1. Precondition (Đợi Namenode)
        - name: SERVICE_PRECONDITION
          value: "namenode:9870"
        
        # 2. BUỘC DATANODE ĐĂNG KÝ BẰNG TÊN POD (datanode-0)
        # Fix lỗi Hostname Check (DFS_CONF_dfs_datanode_hostname)
        - name: DFS_CONF_dfs_datanode_hostname
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        # ---------------------------------
        
        volumeMounts:
        - name: datanode-data
          mountPath: /hadoop/dfs/data
  volumeClaimTemplates:
  - metadata:
      name: datanode-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi