apiVersion: v1
kind: Service
metadata:
  name: namenode
spec:
  type: NodePort  # <--- Đã đổi thành NodePort
  ports:
    - port: 9870
      name: web
      nodePort: 30070 # <--- Cố định cổng này để bạn dễ truy cập từ ngoài
      targetPort: 9870
    - port: 9000
      name: hdfs
      # Cổng RPC 9000 không cần NodePort cố định cũng được, 
      # hoặc bạn có thể để 30090 nếu muốn
  selector:
    app: namenode

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: namenode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: namenode
  template:
    metadata:
      labels:
        app: namenode
    spec:
      containers:
      - name: namenode
        image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
        envFrom:
        - configMapRef:
            name: hadoop-config
        env:
        - name: SERVICE_PRECONDITION
          value: ""
        ports:
        - containerPort: 9870
        - containerPort: 9000
        volumeMounts:
        - name: namenode-data
          mountPath: /hadoop/dfs/name
      volumes:
      - name: namenode-data
        emptyDir: {}